(function(){
  let active='global', privateUid=null, unsubscribe=null, recorder=null, chunks=[];
  const $=id=>document.getElementById(id); const esc=AlfredCore.esc;
  function path(){if(active==='notifications')return 'notifications/'+AlfredCore.currentUser().uid;return active==='private'?'chats/private/'+[AlfredCore.currentUser().uid,privateUid].sort().join('/'):'chats/'+active}
  function listen(){if(unsubscribe)unsubscribe();const ref=AlfredCore.dbRef(path()).orderByChild('at').limitToLast(100);const cb=s=>{const rows=[];s.forEach(c=>rows.push({id:c.key,...(c.val()||{})}));$('messages').innerHTML=rows.map(m=>m.voiceUrl?`<div class="msg"><b>${esc(m.username)}</b><audio controls src="${esc(m.voiceUrl)}"></audio><small>${new Date(m.at||Date.now()).toLocaleString('id-ID')}</small></div>`:`<div class="msg"><b>${esc(m.username)}</b><p>${esc(m.text)}</p><small>${new Date(m.at||Date.now()).toLocaleString('id-ID')}</small></div>`).join('')||'<div class="notice">Belum ada pesan.</div>';$('messages').scrollTop=$('messages').scrollHeight};ref.on('value',cb);unsubscribe=()=>ref.off('value',cb)}
  async function selectChannel(c){active=c;document.querySelectorAll('[data-channel]').forEach(x=>x.classList.toggle('active',x.dataset.channel===c));$('privateBox').classList.toggle('hidden',c!=='private');if(c!=='private'){privateUid=null;listen()}}
  async function send(){const t=$('chatText').value.trim();if(!t||active==='notifications'||active==='private'&&!privateUid)return;await AlfredCore.sendChat(active,t,privateUid);$('chatText').value=''}
  async function choosePrivate(){const term=$('privateUser').value.trim();const users=await AlfredCore.findUsers(term);$('userResults').innerHTML=users.map(u=>`<button class="btn alt userpick" data-uid="${u.uid}" data-name="${esc(u.username)}">${esc(u.username)} <small>${u.role}</small></button>`).join('')||'<span class="muted">Tidak ditemukan.</span>';document.querySelectorAll('.userpick').forEach(b=>b.onclick=()=>{privateUid=b.dataset.uid;$('privateTarget').textContent='Chat pribadi: '+b.dataset.name;listen()})}
  async function recordVoice(){if(!navigator.mediaDevices?.getUserMedia){alert('Browser tidak mendukung mikrofon.');return}if(recorder&&recorder.state==='recording'){recorder.stop();$('voiceBtn').textContent='🎙️ Voice Note';return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());try{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});await AlfredCore.sendVoiceNote(active,privateUid,{blob});}catch(e){alert('Voice note gagal: '+e.message)}};recorder.start();$('voiceBtn').textContent='⏹️ Stop & Kirim'}
  // Basic WebRTC room: small-room voice chat using RTDB signaling. For large classes, use an SFU later.
  let pcMap={}, localStream=null, roomRef=null;
  async function joinVoice(){if(!navigator.mediaDevices?.getUserMedia)return alert('Browser tidak mendukung mikrofon.');if(localStream)return;localStream=await navigator.mediaDevices.getUserMedia({audio:true});$('voiceStatus').textContent='🎙️ Voice room aktif';const me=AlfredCore.currentUser().uid;roomRef=AlfredCore.dbRef('voiceRooms/global');await roomRef.child(me).set({joined:true,at:firebase.database.ServerValue.TIMESTAMP});roomRef.child(me).onDisconnect().remove();const snap=await roomRef.once('value');snap.forEach(c=>{if(c.key!==me)makePeer(c.key,true)});roomRef.on('child_added',c=>{if(c.key!==me&&!pcMap[c.key])makePeer(c.key,false)});roomRef.on('child_removed',c=>{if(pcMap[c.key]){pcMap[c.key].close();delete pcMap[c.key]}})}
  async function makePeer(peer,initiator){const me=AlfredCore.currentUser().uid;const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pcMap[peer]=pc;localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.onicecandidate=e=>{if(e.candidate)AlfredCore.dbRef('voiceSignals/'+peer+'/'+me+'/candidates').push(e.candidate.toJSON())};pc.ontrack=e=>{let a=document.getElementById('audio-'+peer);if(!a){a=document.createElement('audio');a.id='audio-'+peer;a.autoplay=true;a.controls=true;$('remoteAudios').appendChild(a)}a.srcObject=e.streams[0]};const signal=AlfredCore.dbRef('voiceSignals/'+me+'/'+peer);signal.child('offer').on('value',async s=>{if(s.exists()&&!pc.currentRemoteDescription){await pc.setRemoteDescription(s.val());const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await AlfredCore.dbRef('voiceSignals/'+peer+'/'+me+'/answer').set({type:ans.type,sdp:ans.sdp})}});signal.child('answer').on('value',async s=>{if(initiator&&s.exists()&&!pc.currentRemoteDescription)await pc.setRemoteDescription(s.val())});signal.child('candidates').on('child_added',s=>{pc.addIceCandidate(s.val()).catch(()=>{})});if(initiator){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await signal.set({offer:{type:offer.type,sdp:offer.sdp}})}}
  async function leaveVoice(){const me=AlfredCore.currentUser()?.uid;if(roomRef&&me){roomRef.child(me).remove();roomRef.off();}Object.values(pcMap).forEach(p=>p.close());pcMap={};if(localStream)localStream.getTracks().forEach(t=>t.stop());localStream=null;$('voiceStatus').textContent='Voice room tidak aktif';$('remoteAudios').innerHTML=''}
  document.addEventListener('DOMContentLoaded',async()=>{const u=await AlfredCore.requireStudent();if(!u)return;document.querySelectorAll('[data-channel]').forEach(b=>b.onclick=()=>selectChannel(b.dataset.channel));$('sendBtn').onclick=send;$('voiceBtn').onclick=recordVoice;$('privateSearch').onclick=choosePrivate;$('joinVoice').onclick=joinVoice;$('leaveVoice').onclick=leaveVoice;listen();});
})();
