/* Alfred Mandarin Vocabulary Bank
   level uses HSK 1-6 and HSK 7-9 as the app's learning bands.
   Review the exact official HSK syllabus before publishing a claim that a word belongs to a specific official list.
*/
window.VOCABULARY=[
['我','wǒ','saya / aku','HSK1','pronoun'],['你','nǐ','kamu','HSK1','pronoun'],['他','tā','dia (laki-laki)','HSK1','pronoun'],['她','tā','dia (perempuan)','HSK1','pronoun'],['我们','wǒmen','kami / kita','HSK1','pronoun'],['你们','nǐmen','kalian','HSK1','pronoun'],['他们','tāmen','mereka','HSK1','pronoun'],['是','shì','adalah','HSK1','basic'],['不','bù','tidak / bukan','HSK1','basic'],['有','yǒu','punya / ada','HSK1','basic'],['没有','méiyǒu','tidak punya / tidak ada','HSK1','basic'],['好','hǎo','baik / bagus','HSK1','adjective'],['很','hěn','sangat','HSK1','adverb'],['也','yě','juga','HSK1','adverb'],['都','dōu','semua','HSK1','adverb'],['吗','ma','partikel pertanyaan','HSK1','grammar'],['谁','shéi','siapa','HSK1','question'],['什么','shénme','apa','HSK1','question'],['哪里','nǎlǐ','di mana','HSK1','question'],['多少','duōshao','berapa','HSK1','question'],['几','jǐ','berapa (jumlah kecil)','HSK1','question'],['怎么','zěnme','bagaimana','HSK1','question'],['吃','chī','makan','HSK1','verb'],['喝','hē','minum','HSK1','verb'],['学','xué','belajar','HSK1','education'],['看','kàn','melihat / membaca','HSK1','verb'],['听','tīng','mendengar','HSK1','verb'],['说','shuō','berbicara / mengatakan','HSK1','verb'],['去','qù','pergi','HSK1','verb'],['来','lái','datang','HSK1','verb'],['喜欢','xǐhuan','suka','HSK1','feeling'],['爱','ài','mencintai / suka','HSK1','feeling'],['想','xiǎng','ingin / berpikir','HSK1','verb'],['知道','zhīdào','tahu','HSK1','verb'],['认识','rènshi','mengenal','HSK1','verb'],['水','shuǐ','air','HSK1','food'],['饭','fàn','nasi / makanan','HSK1','food'],['茶','chá','teh','HSK1','food'],['咖啡','kāfēi','kopi','HSK1','food'],['苹果','píngguǒ','apel','HSK1','food'],['猫','māo','kucing','HSK1','animal'],['狗','gǒu','anjing','HSK1','animal'],['书','shū','buku','HSK1','education'],['老师','lǎoshī','guru','HSK1','education'],['学生','xuésheng','pelajar','HSK1','education'],['朋友','péngyou','teman','HSK1','people'],['家','jiā','rumah / keluarga','HSK1','people'],['人','rén','orang','HSK1','people'],['中国','Zhōngguó','Tiongkok / China','HSK1','place'],['中文','Zhōngwén','bahasa Mandarin','HSK1','language'],
['现在','xiànzài','sekarang','HSK2','time'],['今天','jīntiān','hari ini','HSK1','time'],['明天','míngtiān','besok','HSK1','time'],['昨天','zuótiān','kemarin','HSK1','time'],['时间','shíjiān','waktu','HSK2','time'],['工作','gōngzuò','bekerja / pekerjaan','HSK2','work'],['学习','xuéxí','belajar','HSK2','education'],['问题','wèntí','pertanyaan / masalah','HSK2','abstract'],['帮助','bāngzhù','membantu / bantuan','HSK2','verb'],['开始','kāishǐ','mulai','HSK2','verb'],['结束','jiéshù','selesai / mengakhiri','HSK2','verb'],['因为','yīnwèi','karena','HSK2','grammar'],['所以','suǒyǐ','jadi / oleh karena itu','HSK2','grammar'],['但是','dànshì','tetapi','HSK2','grammar'],['如果','rúguǒ','jika','HSK3','grammar'],['觉得','juéde','merasa / berpendapat','HSK3','verb'],['希望','xīwàng','berharap','HSK3','feeling'],['需要','xūyào','membutuhkan','HSK3','verb'],['决定','juédìng','memutuskan','HSK3','verb'],['重要','zhòngyào','penting','HSK3','adjective'],['方便','fāngbiàn','nyaman / praktis','HSK3','adjective'],['了解','liǎojiě','memahami / mengetahui','HSK3','verb'],['发现','fāxiàn','menemukan','HSK4','verb'],['经验','jīngyàn','pengalaman','HSK4','abstract'],['机会','jīhuì','kesempatan','HSK4','abstract'],['计划','jìhuà','rencana','HSK4','abstract'],['环境','huánjìng','lingkungan','HSK4','abstract'],['社会','shèhuì','masyarakat','HSK4','society'],['文化','wénhuà','budaya','HSK4','society'],['提高','tígāo','meningkatkan','HSK4','verb'],['能力','nénglì','kemampuan','HSK4','abstract'],['成功','chénggōng','sukses / berhasil','HSK4','abstract'],['责任','zérèn','tanggung jawab','HSK5','abstract'],['发展','fāzhǎn','perkembangan / mengembangkan','HSK5','abstract'],['影响','yǐngxiǎng','pengaruh / memengaruhi','HSK5','abstract'],['解决','jiějué','menyelesaikan','HSK5','verb'],['选择','xuǎnzé','memilih / pilihan','HSK5','verb'],['表达','biǎodá','mengungkapkan','HSK5','communication'],['目标','mùbiāo','tujuan / target','HSK5','abstract'],['观点','guāndiǎn','sudut pandang','HSK6','academic'],['资源','zīyuán','sumber daya','HSK6','academic'],['复杂','fùzá','rumit / kompleks','HSK6','adjective'],['分析','fēnxī','menganalisis / analisis','HSK6','academic'],['原则','yuánzé','prinsip','HSK6','academic'],['现象','xiànxiàng','fenomena','HSK6','academic'],['趋势','qūshì','tren / kecenderungan','HSK6','academic']
].map((x,i)=>({id:i+1,hanzi:x[0],pinyin:x[1],meaning:x[2],level:x[3],category:x[4]}));
window.getVocabulary=()=>window.VOCABULARY.slice();
